version: '3.8'

services:
    # PHP Service
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: getfly_adapter
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - redis

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: getfly_adapter_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

    # Redis Service
    redis:
        image: redis:alpine
        container_name: getfly_adapter_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_network

# Define network
networks:
    laravel_network:
        driver: bridge

# Define volumes
volumes:
    mysql_data:
